services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    container_name: fastapi_server_container
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data: